module.exports = {
  env: {
    node: true,
    commonjs: true,
    "jest/globals": true,
  },
  extends: [
    "airbnb-typescript/base",
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier",
  ],
  plugins: ["@typescript-eslint", "jest"],
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/ban-ts-ignore": 0,
    "@typescript-eslint/ban-types": 0,
    "@typescript-eslint/camelcase": 0,
    "react-native/split-platform-components": 0,
    "@typescript-eslint/explicit-function-return-type": 0,
    "@typescript-eslint/member-delimiter-style": 0,
    "@typescript-eslint/no-empty-interface": 0,
    "@typescript-eslint/no-explicit-any": 1,
    "@typescript-eslint/consistent-generic-constructors": "error",
    "@typescript-eslint/no-unused-vars": 1,
    "@typescript-eslint/no-use-before-define": 0,
    "@typescript-eslint/no-var-requires": 0,
    "arrow-parens": 0,
    "arrow-spacing": 1,
    camelcase: 1,
    "class-methods-use-this": 0,
    "comma-dangle": [
      "error",
      {
        arrays: "always-multiline",
        objects: "always-multiline",
        imports: "always-multiline",
        exports: "always-multiline",
        functions: "always-multiline",
      },
    ],
    "consistent-return": 0,
    "implicit-arrow-linebreak": 0,
    "import/extensions": 0,
    "import/no-extraneous-dependencies": 0,
    "import/no-unresolved": 0,
    "import/order": 0,
    "import/prefer-default-export": 0,
    "no-case-declarations": 0,
    "no-console": 0,
    "no-duplicate-case": 0,
    "no-fallthrough": 0,
    "no-plusplus": 0,
    "@typescript-eslint/no-shadow": 1,
    "no-shadow": 0,
    "no-underscore-dangle": 0,
    "global-require": 0,
    "no-restricted-exports": 0,
    "no-unused-vars": 0,
    "no-use-before-define": 0,
    semi: 0,
    "spaced-comment": 1,
    "prefer-template": 2,
    "@typescript-eslint/no-explicit-any": 1,
    "@typescript-eslint/array-type": 2,
    "@typescript-eslint/consistent-generic-constructors": 2,
    "@typescript-eslint/consistent-indexed-object-style": 2,
    "dot-notation": 0,
    "@typescript-eslint/dot-notation": 2,
    "max-params": 0,
    "@typescript-eslint/max-params": 2,
    "@typescript-eslint/method-signature-style": [2, "method"],
    "@typescript-eslint/no-array-delete": 2,
    "@typescript-eslint/no-base-to-string": 2,
    "@typescript-eslint/no-duplicate-enum-values": 2,
    "@typescript-eslint/no-extra-non-null-assertion": 2,
    "@typescript-eslint/no-for-in-array": 2,
    "no-implied-eval": 0,
    "@typescript-eslint/no-implied-eval": 2,
    "@typescript-eslint/restrict-plus-operands": [2],
    "@typescript-eslint/lines-between-class-members": 0,
    "react-native/split-platform-components": 0,
    eqeqeq: 2,
    "max-depth": [2, 3],
    "no-alert": 2,
    "prefer-arrow-callback": 2,
    yoda: 2,
    "max-lines": [2, 300],
    "max-statements": [2, 30],
  },
}
