module.exports = {
  env: {
    node: true,
    commonjs: true,
    "jest/globals": true,
  },
  extends: ["airbnb", "prettier", "eslint:recommended", "plugin:@typescript-eslint/recommended"],
  plugins: ["@typescript-eslint", "jest"],
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/ban-ts-ignore": 0,
    "@typescript-eslint/ban-types": 0,
    "@typescript-eslint/camelcase": 0,
    "@typescript-eslint/explicit-function-return-type": 0,
    "@typescript-eslint/member-delimiter-style": 0,
    "@typescript-eslint/no-empty-interface": 0,
    "@typescript-eslint/no-explicit-any": 0,
    "@typescript-eslint/no-unused-vars": 1,
    "@typescript-eslint/no-use-before-define": 0,
    "@typescript-eslint/no-var-requires": 0,
    "arrow-parens": 0,
    "arrow-spacing": 1,
    camelcase: 1,
    "class-methods-use-this": 0,
    "comma-dangle": [
      "error",
      {
        arrays: "always-multiline",
        objects: "always-multiline",
        imports: "always-multiline",
        exports: "always-multiline",
        functions: "always-multiline",
      },
    ],
    "consistent-return": 0,
    "implicit-arrow-linebreak": 0,
    "import/extensions": 0,
    "import/no-extraneous-dependencies": 0,
    "import/no-unresolved": 0,
    "import/order": 0,
    "import/prefer-default-export": 0,
    "no-case-declarations": 0,
    "no-console": 0,
    "no-duplicate-case": 0,
    "no-fallthrough": 0,
    "no-plusplus": 0,
    "no-shadow": 1,
    "no-underscore-dangle": 0,
    "no-unused-vars": 0,
    "no-use-before-define": 0,
    semi: 0,
    "spaced-comment": 1,
  },
}
